### ISSUE TITLE
When will the source code be released?

### ISSUE THREAD

**Issue by umar-mq** [adobe-research/dynasaur#1]
Any estimated date?

**Comment by dangne** [comment]
Hi, we have released our code! Please let us know if there are any problems.

**Comment by bendikrb** [comment]
Some, at least half-working, code would be nice too!
After putting HF token in place + adding a fair bit of missing code for using OpenAI instead of Azure, I gave up at;
`transformers.agents.agents.AgentGenerationError: Error in generating llm output: Object of type ModelMetaclass is not JSON serializable.`

Good luck!
